services:
  dev:
    image: garrybot
    env_file:
      - ~/.env/.env.development
    build:
      context: .
      dockerfile: GarryBot/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug

  prod:
    image: garrybot
    env_file:
      - ~/.env/.env.production
    build:
      context: .
      dockerfile: GarryBot/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    restart: unless-stopped